config/routes.rb
Rails.application.routes.draw do
  resources :thoughts
  root 'thoughts#index'

end

app/models/thought.rb
class Thought < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController	

	def index
		@thought = Thought.new
		@thoughts = Thought.order(created_at: :desc).all
	end

	def show 
		@thought = Thought.find(params[:id])
	end

	def edit
		@thought = Thought.find(params[:id])
	end

	def update
		@thought = Thought.find(params[:id])
		if @thought.update_attributes(allowed_params)
			respond_to do |format|
      		format.html { redirect_to thoughts_path, notice: 'Thought was successfully updated.' }
			end
		else
			render 'edit'
		end
	end

	def new
		@thought = Thought.new
	end

	def create
		@thought = Thought.new(allowed_params)
		if @thought.save
			respond_to do |format|
      		format.html { redirect_to thoughts_path, notice: 'Thought was successfully created.' }
			end
		else 
			render 'new'
		end
	end

	def destroy
		@thought = Thought.find(params[:id])
		@thought.destroy
		respond_to do |format|
      		format.html { redirect_to thoughts_path, notice: 'Thought was successfully deleted.' }
      	end
	end

	private 

	def allowed_params
		params.require(:thought).permit(:title, :text, :source)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Thoughts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/thoughts/edit.haml
.thought
	= form_for @thought do |f|
		= f.text_field :title, placeholder: "Title", size: "50x2"
		%br
		%br
		= f.text_area :text, placeholder: "Text", size: "50x7"
		%br
		%br
		= f.text_field :source, placeholder: "Source", size: "83x2"
		%br
		%br
		= f.submit "Update"
		%br
		%br
	.action
		= link_to "Go Back", thoughts_path

app/views/thoughts/index.haml
= notice
%br

%h1= Thoughts
%br


= form_for @thought do |f|
	= f.text_field :title, placeholder: "Title" 
	%br
	%br
	= f.text_area :text, placeholder: "Your Thought", size: "25x7"
	%br
	%br
	= f.text_field :source, placeholder: "Source"
	%br
	%br
	= f.submit "Create"
	%br
	%br

.content
	- @thoughts.each do |thought|
		.thought
			.title
				= thought.title.html_safe
			%p= thought.text.html_safe
			.source
				= thought.source.html_safe
			.info
				%i
					Created :
					=thought.created_at.strftime("%d %b. %Y")
					|
					Updated :
					=thought.updated_at.strftime("%d %b. %Y")
			.action
				= link_to "Edit", edit_thought_path(thought)
				|
				= link_to "Delete", thought, method: :delete, data: { confirm: 'Are you sure?'}
		.space

app/views/thoughts/show.haml
%h3= @thought.title.html_safe
%p= @thought.text.html_safe
%i= @thought.source.html_safe
%br
%h5
	%i
		Created :
		= @thought.created_at.strftime("%d %b. %Y")
		|
		Updated :
		= @thought.updated_at.strftime("%d %b. %Y")

= link_to "Edit", edit_thought_path(@thought)
|
= link_to "Delete", @thought, method: :delete, data: { confirm: 'Are you sure?'}
%br
%br
= link_to "Go Back", thoughts_path